server:
  port: 82
  servlet:
    session:
      persistent: false
    timeout: 1800
    context-path: /ssoclient
sso:
  server: http://localhost/ssoserver
  tokenRefreshTime: 1

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      port: 35728
# 日志配置
logging:
  level:
    org.springframework: debug
