server:
  port: 80
  servlet:
    context-path: /ssoserver
    session:
      timeout: 1800

spring:
  thymeleaf:
    cache: false
    suffix: .html
    encoding: utf-8
    enabled: true
  devtools:
    livereload:
      port: 35729